.github/workspace/pr-main.yml

ci to run tests and lints on the packages

add workflow yml

---

.changeset/mean-oranges-poke.md
packages/ui/src/components/button.tsx
packages/ui/src/components/input.tsx
packages/ui/src/components/modal.tsx
packages/ui/src/components/multistep.tsx
packages/ui/src/components/popover.tsx
packages/ui/src/components/typography.tsx
packages/ui/src/helpers/variants.ts
packages/ui/src/plugAndPlay/connectWallet/authorization.tsx
packages/ui/src/plugAndPlay/connectWallet/processingTransaction.tsx

This pull request introduces several updates to enhance the functionality and customization options of various components within the codebase.
- Local state has been replaced with a state and action provided by the parent component, facilitating better state management.
- Removed overflow and max-height properties to provide better control over the customization of custom components.
- Added a new resetOnUnmount prop to reset the default state when the component is unmounted.
- Introduced a placement prop for Multistep Interactive.
- Eliminated overflow for improved customization control over custom components.
- Adjusted the default typography text size to sm from md for a more refined appearance.
- Implemented a fix to remove a potential loop scenario when there are no extension …

fix: component improvements

---

.changeset/smooth-plants-visit.md
packages/ui/src/components/interaction.tsx
packages/ui/src/components/loading.tsx
packages/ui/src/icons/creditCard.tsx

This pull request addresses multiple enhancements:
closes https://github.com/Polkadex-Substrate/polkadex-ts/issues/38

Addressing Component fixes

---

packages/react-providers/src/ExtensionAccountsProvider/useExtensionAccounts.tsx
packages/react-providers/src/ExtensionsProvider/useExtensions.tsx
packages/react-providers/src/UserAccountsProvider/index.ts
packages/react-providers/src/UserAccountsProvider/provider.tsx
packages/react-providers/src/UserAccountsProvider/types.ts
packages/react-providers/src/UserAccountsProvider/useUserAccounts.tsx
packages/react-providers/src/index.ts
yarn.lock

- throw error if context is not defined
- add hook to access local accounts in keyring

Provider hook improvements

---

.changeset/cool-cougars-speak.md
packages/react-providers/src/ExtensionsProvider/constants.ts
packages/react-providers/src/ExtensionsProvider/provider.tsx
packages/react-providers/src/ExtensionsProvider/types.ts

This pull request addresses the client-side compatibility issue encountered in the @polkadot-cloud/assets package by transitioning to a dynamic import approach.
Close: https://github.com/Polkadex-Substrate/polkadex-ts/issues/51

Resolve Client-Side Compatibility Issue in @polkadot-cloud/assets Package with Dynamic Import 

---

.changeset/mean-jars-beam.md
packages/ui/package.json
packages/ui/src/components/hoverCard.tsx
packages/ui/src/components/index.ts
themeConfig.ts

This pull request addresses the feature request for the implementation of a "Reusable Hover-Triggered Component." The proposed component aims to provide a seamless and intuitive hover interaction, distinct from traditional tooltips, offering enhanced flexibility and interactivity.
https://github.com/Polkadex-Substrate/polkadex-ts/assets/12574469/ea687e24-4d10-4292-9e7f-cb16fc297a32
Close: https://github.com/Polkadex-Substrate/polkadex-ts/issues/62

Feature Request - Reusable Hover-Triggered Component

---

.changeset/orange-readers-applaud.md
packages/ui/package.json
packages/ui/src/components/index.ts
packages/ui/src/components/toaster.tsx

This pull request addresses the feature request for the implementation of a "Toast Component." The proposed component serves as an essential UI element for providing non-intrusive feedback and notifications to users, enhancing the overall user experience.
https://github.com/Polkadex-Substrate/polkadex-ts/assets/12574469/c608bc2e-1b2c-4203-a209-204b3468c94e
Close: https://github.com/Polkadex-Substrate/polkadex-ts/issues/60

Feature Request - Toast Component 

---

.changeset/tricky-oranges-work.md
packages/ui/package.json
packages/ui/src/components/drawer.tsx
packages/ui/src/components/index.ts

This pull request addresses the feature request for the implementation of a "Responsive Drawer Component". The proposed component aims to provide a responsive and dynamic alternative to traditional modals, ensuring optimal usability across various devices and screen sizes.
https://github.com/Polkadex-Substrate/polkadex-ts/assets/12574469/d5e4231c-b3de-4a90-ab90-a5807a806b9e
Close: https://github.com/Polkadex-Substrate/polkadex-ts/issues/61

Feature Request - Responsive Drawer Component

---

.changeset/fifty-seas-cheat.md
packages/ui/package.json
packages/ui/src/components/multistep.tsx

This pull request addresses the previous collision problem, where manual positioning of the content was required. The issue became apparent when multiple contents with varying sizes were added, causing layout distortions. In this update, we eliminate manual positioning and introduce an automatic positioning mechanism to alleviate this challenge.
https://github.com/Polkadex-Substrate/polkadex-ts/assets/12574469/85d6ceba-128a-4396-8388-a999124cd6c7
Close: https://github.com/Polkadex-Substrate/polkadex-ts/issues/69

Collision Handling in Multistep Component

---

.changeset/hip-eggs-arrive.md
packages/ui/package.json
packages/ui/src/components/index.ts
packages/ui/src/components/tabs.tsx

This pull request introduces a new tabs component to enhance the user interface within the @polkadex/ux package. The new component provides a modular and customizable solution for incorporating tabbed navigation in different sections.
Close: https://github.com/Polkadex-Substrate/polkadex-ts/issues/74

Tabs Component in @polkadex/ux Package

---

.changeset/violet-comics-pretend.md
packages/ui/src/components/index.ts
packages/ui/src/components/table.tsx

This pull request introduces a new table component to enhance data presentation and user interaction within the @polkadex/ux package.
Close: https://github.com/Polkadex-Substrate/polkadex-ts/issues/75

Table Component for @polkadex/ux Package

---

.changeset/tame-lions-swim.md
packages/polkadex-api/package.json
packages/polkadex-api/src/base-api.ts
packages/polkadex-api/src/index.ts
packages/polkadex-api/src/modules/balances.ts
packages/polkadex-api/src/modules/index.ts
packages/polkadex-api/src/modules/ocex.ts
packages/polkadex-api/tsconfig.json
packages/types/src/chain.ts
yarn.lock

- create basic modules for query and extrinsic on ocex pallet

basic modules api for polkadex chain

---

.changeset/cuddly-cooks-wait.md
packages/ui/src/plugAndPlay/connectWallet/connectWallet.tsx

This PR aims to fix the dead links of privacy policy and terms of service.

Dead Links fix

---

.changeset/bright-dryers-thank.md
packages/ui/src/components/button.tsx
packages/ui/src/components/dropdown.tsx
packages/ui/src/components/input.tsx
packages/ui/src/components/interaction.tsx
packages/ui/src/components/popover.tsx
packages/ui/src/components/table.tsx
packages/ui/src/components/tabs.tsx
packages/ui/src/components/typography.tsx
packages/ui/src/helpers/index.ts
packages/ui/src/helpers/typeofChildren.ts
packages/ui/src/plugAndPlay/connectWallet/authorization.tsx
packages/ui/src/plugAndPlay/connectWallet/connectWallet.tsx
packages/ui/src/plugAndPlay/connectWallet/extensionAccounts.tsx
packages/ui/src/plugAndPlay/connectWallet/processingTransaction.tsx
packages/ui/src/readyToUse/chainCard.tsx
packages/ui/src/readyToUse/providerCard.tsx
themeConfig.ts

This pull request addresses several improvements and enhancements across our application's UI and functionality. Here's a summary of the key changes:
Close: https://github.com/Polkadex-Substrate/polkadex-ts/issues/88

 Bug Fixes for Component Styling and Functionality

---

.changeset/selfish-doors-draw.md
packages/local-wallets/package.json
packages/local-wallets/src/GDriveStorage/GDrive/api.ts
packages/local-wallets/src/GDriveStorage/GDrive/drive.ts
packages/local-wallets/src/GDriveStorage/GDrive/oauth.ts
packages/local-wallets/src/GDriveStorage/GDrive/utils.ts
packages/local-wallets/src/GDriveStorage/index.ts
packages/local-wallets/src/GDriveStorage/types.ts
packages/local-wallets/src/index.ts
packages/local-wallets/tsconfig.json
yarn.lock

Add module for account strorage using google drive

feat: add gdrive store

---

.changeset/honest-peaches-try.md
packages/local-wallets/package.json
packages/local-wallets/src/index.ts
packages/numericals/jest.config.js
packages/numericals/package.json
packages/numericals/src/index.test.ts
packages/numericals/src/index.ts
packages/polkadex-api/jest.config.js
packages/polkadex-api/package.json
packages/polkadex-api/src/base-api.ts
packages/polkadex-api/src/modules/balances.ts
packages/polkadex-api/src/modules/index.ts
packages/polkadex-api/src/modules/ocex.ts
packages/polkadex-api/src/modules/swap.test.ts
packages/polkadex-api/src/modules/swap.ts
packages/polkadex-api/src/types.ts
packages/react-providers/package.json
packages/types/package.json
packages/types/src/chain.ts
packages/utils/package.json
yarn.lock

- queries and extrincs to interact with the swap pallet of polkadex.

feat: Swap api

---

.changeset/metal-schools-smell.md
packages/ui/src/components/filterGroup.tsx
packages/ui/src/components/index.ts

This pull request introduces a new compact filter component to address the issue of oversized dropdowns in certain areas of Polkadex products apps, particularly small elements like tables. The compact filter component offers a more streamlined and space-efficient solution for filtering data without sacrificing functionality.
https://github.com/Polkadex-Substrate/polkadex-ts/assets/12574469/df5b7355-8b24-4f5b-af67-0b2e2f730c5f
Close: https://github.com/Polkadex-Substrate/polkadex-ts/issues/109

feat: FilterGroup component

---

.changeset/gold-suits-reflect.md
packages/ui/package.json
packages/ui/src/components/index.ts
packages/ui/src/components/toggleGroup.tsx

This pull request introduces a new Toggle Group component to enhance the user experience and provide a more intuitive interface for selecting options within Polkadex products. The Toggle Group component allows users to toggle between different options, providing a clear visual indication of the selected option.
https://github.com/Polkadex-Substrate/polkadex-ts/assets/12574469/6af98890-21dd-49a3-bd8c-abe650738a7c
Close: https://github.com/Polkadex-Substrate/polkadex-ts/issues/108

feat: Togglegroup component

---

.changeset/fresh-walls-press.md
packages/polkadex-api/src/modules/swap.ts
yarn.lock

fix wrong call to chain specified for `swapTokensForExactTokens` method.

fix: swapTokensForExactTokens caller fix

---

.changeset/great-humans-call.md
packages/polkadex-api/src/modules/swap.test.ts
packages/polkadex-api/src/modules/swap.ts
packages/polkadex-api/src/types.ts

add method to get reservers of a pool.

feat: add get reserves call

---

.changeset/old-elephants-sleep.md
packages/polkadex-api/src/modules/swap.test.ts
packages/polkadex-api/src/modules/swap.ts

Closes https://github.com/Polkadex-Substrate/polkadex-ts/issues/119

fix: handle pool not present

---

.changeset/selfish-apes-build.md
packages/ui/src/components/button.tsx
packages/ui/src/components/checkbox.tsx
packages/ui/src/components/drawer.tsx
packages/ui/src/components/filterGroup.tsx
packages/ui/src/components/input.tsx
packages/ui/src/components/interaction.tsx
packages/ui/src/components/label.tsx
packages/ui/src/components/searchable.tsx
packages/ui/src/components/table.tsx
packages/ui/src/components/toaster.tsx
packages/ui/src/components/toggleGroup.tsx
packages/ui/src/components/tooltip.tsx
packages/ui/src/components/typography.tsx
packages/ui/src/helpers/variants.ts
packages/ui/src/plugAndPlay/connectWallet/authorization.tsx
packages/ui/src/plugAndPlay/connectWallet/connectWallet.tsx
packages/ui/src/plugAndPlay/connectWallet/extensionAccounts.tsx
packages/ui/src/plugAndPlay/connectWallet/processingTransaction.tsx
packages/ui/src/readyToUse/accountCard.tsx
packages/ui/src/readyToUse/chainCard.tsx
packages/ui/src/readyToUse/providerCard.tsx
packages/ui/tailwind.config.ts

This pull request focuses on resolving the issue of default colors within specific components of the project.
Close: https://github.com/Polkadex-Substrate/polkadex-ts/issues/125

Colors Side Effects

---

.changeset/big-pots-suffer.md
packages/ui/package.json
packages/ui/src/components/index.ts
packages/ui/src/components/scrollArea.tsx

This pull request addresses the need for a dedicated component to handle adaptive height within Polkadex apps, specifically accommodating components requiring scroll functionality. Currently, our projects employ an adaptive layout to utilize 100% of the screen size on normal screens, but some components necessitate scrolling.
Close: https://github.com/Polkadex-Substrate/polkadex-ts/issues/128

ScrollArea component

---

.changeset/fuzzy-trains-deliver.md
packages/react-providers/package.json
packages/react-providers/src/ExtensionAccountsProvider/provider.tsx
packages/react-providers/src/ExtensionAccountsProvider/useExtensionAccounts.tsx
packages/react-providers/src/ExtensionAccountsProvider/useImportExtension.tsx
packages/react-providers/src/ExtensionsProvider/provider.tsx
packages/react-providers/src/ExtensionsProvider/useExtensions.tsx
packages/react-providers/src/ExtensionsProvider/utils.ts
packages/react-providers/src/LocalAccountsProvider/provider.tsx
packages/react-providers/src/LocalAccountsProvider/useLocalAccounts.tsx

This pull request addresses the identified bug in the ExtensionsProvider, which causes rendering issues in the Connect wallet functionality.
Close: https://github.com/Polkadex-Substrate/polkadex-ts/issues/133

@polkadex/react-providers patch

---

.changeset/twenty-pandas-promise.md
packages/polkadex-api/src/base-api.ts
packages/polkadex-api/src/modules/constants.ts
packages/polkadex-api/src/modules/index.ts
packages/polkadex-api/src/modules/lmp.ts

- add methods to query latest block
- query start of next epoch
- query current epoch
- create claim rewards transaction 
- query start block for claiming rewards of an epoch

feat: improve lmp api
